// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Approval Workflow', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Approval Workflow', async function() {
    // Test name: Approval Workflow
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:819/")
    // 2 | setWindowSize | 968x870 |  | 
    await driver.manage().window().setRect({ width: 968, height: 870 })
    // 3 | click | linkText=nassco-mis/ |  | 
    await driver.findElement(By.linkText("nassco-mis/")).click()
    // 4 | doubleClick | linkText=nassco-mis/ |  | 
    {
      const element = await driver.findElement(By.linkText("nassco-mis/"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 5 | click | name=email |  | 
    await driver.findElement(By.name("email")).click()
    // 6 | type | name=email | pat2echo@gmail.com | 
    await driver.findElement(By.name("email")).sendKeys("pat2echo@gmail.com")
    // 7 | click | name=email |  | 
    await driver.findElement(By.name("email")).click()
    // 8 | click | name=email |  | 
    await driver.findElement(By.name("email")).click()
    // 9 | doubleClick | name=email |  | 
    {
      const element = await driver.findElement(By.name("email"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 10 | click | name=password |  | 
    await driver.findElement(By.name("password")).click()
    // 11 | click | name=password |  | 
    await driver.findElement(By.name("password")).click()
    // 12 | type | name=password | pat2echo | 
    await driver.findElement(By.name("password")).sendKeys("pat2echo")
    // 13 | click | css=.container-login100-form-btn:nth-child(6) > .login100-form-btn |  | 
    await driver.findElement(By.css(".container-login100-form-btn:nth-child(6) > .login100-form-btn")).click()
    // 14 | mouseOver | css=.container-login100-form-btn:nth-child(6) > .login100-form-btn |  | 
    {
      const element = await driver.findElement(By.css(".container-login100-form-btn:nth-child(6) > .login100-form-btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 15 | mouseOut | css=.container-login100-form-btn:nth-child(6) > .login100-form-btn |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 16 | click | id=swip-tab |  | 
    await driver.findElement(By.id("swip-tab")).click()
    // 17 | mouseOver | id=swip-tab |  | 
    {
      const element = await driver.findElement(By.id("swip-tab"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 18 | mouseOut | id=swip-tab |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 19 | click | css=.vertical-nav-menu > .app-sidebar__heading:nth-child(13) |  | 
    await driver.findElement(By.css(".vertical-nav-menu > .app-sidebar__heading:nth-child(13)")).click()
    // 20 | click | css=li:nth-child(14) .app-sidebar__heading:nth-child(9) |  | 
    await driver.findElement(By.css("li:nth-child(14) .app-sidebar__heading:nth-child(9)")).click()
    // 21 | click | linkText=Submitted |  | 
    await driver.findElement(By.linkText("Submitted")).click()
    // 22 | mouseOver | linkText=Submitted |  | 
    {
      const element = await driver.findElement(By.linkText("Submitted"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 23 | mouseOut | linkText=Submitted |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 24 | click | css=.odd > td:nth-child(4) |  | 
    await driver.findElement(By.css(".odd > td:nth-child(4)")).click()
    // 25 | click | linkText=Submit / Query |  | 
    await driver.findElement(By.linkText("Submit / Query")).click()
    // 27 | click | linkText=Yes, Submit for Approval |  | 
    await driver.findElement(By.linkText("Yes, Submit for Approval")).click()
    // 28 | assertConfirmation | Are you sure that you want to Submit this Business Registration |  | 
    assert(await driver.switchTo().alert().getText() == "Are you sure that you want to Submit this Business Registration")
    // 29 | webdriverChooseOkOnVisibleConfirmation |  |  | 
    await driver.switchTo().alert().accept()
    // 30 | click | id=modal-popup-close |  | 
    await driver.findElement(By.id("modal-popup-close")).click()
    // 31 | click | css=.app-sidebar__heading:nth-child(1) |  | 
    await driver.findElement(By.css(".app-sidebar__heading:nth-child(1)")).click()
    // 32 | click | linkText=Approvals |  | 
    await driver.findElement(By.linkText("Approvals")).click()
    // 33 | click | linkText=View All |  | 
    await driver.findElement(By.linkText("View All")).click()
    // 34 | click | css=.odd:nth-child(1) > td:nth-child(3) |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(3)")).click()
    // 35 | click | linkText=Review |  | 
    await driver.findElement(By.linkText("Review")).click()
    // 36 | mouseOver | linkText=Review |  | 
    {
      const element = await driver.findElement(By.linkText("Review"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 37 | click | linkText=Approve → |  | 
    await driver.findElement(By.linkText("Approve →")).click()
    // 38 | mouseOver | linkText=Approve → |  | 
    {
      const element = await driver.findElement(By.linkText("Approve →"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 40 | mouseOut | linkText=Approve → |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 41 | assertConfirmation | Are you sure that you want to Submit this job |  | 
    assert(await driver.switchTo().alert().getText() == "Are you sure that you want to Submit this job")
    // 42 | webdriverChooseOkOnVisibleConfirmation |  |  | 
    await driver.switchTo().alert().accept()
    // 43 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 44 | type | name=nwp_wf_comment | Okay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Okay")
    // 45 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 46 | mouseOver | css=.col-md-12 > .btn |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 47 | click | id=tab2-handle |  | 
    await driver.findElement(By.id("tab2-handle")).click()
    // 48 | mouseOver | id=tab2-handle |  | 
    {
      const element = await driver.findElement(By.id("tab2-handle"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 49 | mouseOut | id=tab2-handle |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 50 | click | css=.row_selected > td:nth-child(6) > b |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(6) > b")).click()
    // 51 | click | css=.odd:nth-child(1) > td:nth-child(6) > b |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(6) > b")).click()
    // 52 | doubleClick | css=.row_selected > td:nth-child(6) > b |  | 
    {
      const element = await driver.findElement(By.css(".row_selected > td:nth-child(6) > b"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 53 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 54 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 55 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 56 | click | linkText=Confirm Payment |  | 
    await driver.findElement(By.linkText("Confirm Payment")).click()
    // 57 | click | css=.even > td:nth-child(6) |  | 
    await driver.findElement(By.css(".even > td:nth-child(6)")).click()
    // 58 | click | linkText=Confirm Payment |  | 
    await driver.findElement(By.linkText("Confirm Payment")).click()
    // 59 | click | id=eosic_payments396 |  | 
    await driver.findElement(By.id("eosic_payments396")).click()
    // 60 | type | id=eosic_payments396 | 560000 | 
    await driver.findElement(By.id("eosic_payments396")).sendKeys("560000")
    // 61 | click | id=eosic_payments145 |  | 
    await driver.findElement(By.id("eosic_payments145")).click()
    // 62 | type | id=eosic_payments145 | 8969868909 | 
    await driver.findElement(By.id("eosic_payments145")).sendKeys("8969868909")
    // 63 | click | id=form-gen-submit |  | 
    await driver.findElement(By.id("form-gen-submit")).click()
    // 64 | mouseOver | id=form-gen-submit |  | 
    {
      const element = await driver.findElement(By.id("form-gen-submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 65 | mouseOut | id=form-gen-submit |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 66 | click | id=modal-popup-close |  | 
    await driver.findElement(By.id("modal-popup-close")).click()
    // 67 | click | id=tab2-handle |  | 
    await driver.findElement(By.id("tab2-handle")).click()
    // 68 | mouseOver | id=tab2-handle |  | 
    {
      const element = await driver.findElement(By.id("tab2-handle"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 69 | mouseOut | id=tab2-handle |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 70 | click | css=.odd:nth-child(1) > td:nth-child(5) |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(5)")).click()
    // 71 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 72 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 73 | click | id=dynamic |  | 
    await driver.findElement(By.id("dynamic")).click()
    // 74 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 75 | click | css=.odd > td:nth-child(3) |  | 
    await driver.findElement(By.css(".odd > td:nth-child(3)")).click()
    // 76 | click | linkText=Confirm Payment |  | 
    await driver.findElement(By.linkText("Confirm Payment")).click()
    // 77 | mouseOver | linkText=Confirm Payment |  | 
    {
      const element = await driver.findElement(By.linkText("Confirm Payment"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 78 | mouseOut | linkText=Confirm Payment |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 79 | click | id=eosic_payments396 |  | 
    await driver.findElement(By.id("eosic_payments396")).click()
    // 80 | type | id=eosic_payments396 | 96357844 | 
    await driver.findElement(By.id("eosic_payments396")).sendKeys("96357844")
    // 81 | type | id=eosic_payments145 | 14589777 | 
    await driver.findElement(By.id("eosic_payments145")).sendKeys("14589777")
    // 82 | click | id=form-gen-submit |  | 
    await driver.findElement(By.id("form-gen-submit")).click()
    // 83 | mouseOver | id=form-gen-submit |  | 
    {
      const element = await driver.findElement(By.id("form-gen-submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 84 | click | id=modal-popup-close |  | 
    await driver.findElement(By.id("modal-popup-close")).click()
    // 85 | click | id=tab2-handle |  | 
    await driver.findElement(By.id("tab2-handle")).click()
    // 86 | click | css=.odd:nth-child(1) > td:nth-child(5) |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(5)")).click()
    // 87 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 88 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 89 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 90 | type | name=nwp_wf_comment | OKay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("OKay")
    // 91 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 92 | mouseOver | css=.col-md-12 > .btn |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 93 | mouseOut | css=.processing-ajax-request |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 94 | click | css=.row_selected > td:nth-child(6) |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(6)")).click()
    // 95 | click | css=.odd:nth-child(1) > td:nth-child(6) |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(6)")).click()
    // 96 | doubleClick | css=.row_selected > td:nth-child(6) |  | 
    {
      const element = await driver.findElement(By.css(".row_selected > td:nth-child(6)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 97 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 98 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 99 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 100 | type | name=nwp_wf_comment | Okay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Okay")
    // 101 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 102 | mouseOver | css=.col-md-12 > .btn |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 103 | mouseOut | css=.processing-ajax-request |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 104 | click | css=.row_selected > td:nth-child(5) |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(5)")).click()
    // 105 | click | css=.odd:nth-child(1) > td:nth-child(5) |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(5)")).click()
    // 106 | doubleClick | css=.row_selected > td:nth-child(5) |  | 
    {
      const element = await driver.findElement(By.css(".row_selected > td:nth-child(5)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 107 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 108 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 109 | mouseOver | linkText=Approve |  | 
    {
      const element = await driver.findElement(By.linkText("Approve"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 110 | mouseOut | css=.btn-group:nth-child(2) li:nth-child(1) > .custom-single-selected-record-button |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 111 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 112 | type | name=nwp_wf_comment | Okay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Okay")
    // 113 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 114 | mouseOver | css=.col-md-12 > .btn |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 115 | mouseOut | css=.processing-ajax-request |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 116 | click | css=.row_selected > td:nth-child(6) |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(6)")).click()
    // 117 | click | css=.odd:nth-child(1) > td:nth-child(6) |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(6)")).click()
    // 118 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 119 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 120 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 121 | type | name=nwp_wf_comment | Okay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Okay")
    // 122 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 123 | click | css=.row_selected > td:nth-child(6) |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(6)")).click()
    // 124 | click | css=.odd:nth-child(1) > td:nth-child(6) |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(6)")).click()
    // 125 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 126 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 127 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 128 | type | name=nwp_wf_comment | Okay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Okay")
    // 129 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 130 | click | css=.row_selected > td:nth-child(5) |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(5)")).click()
    // 131 | click | css=.odd:nth-child(1) > td:nth-child(5) |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(5)")).click()
    // 132 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 133 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 134 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 135 | click | linkText=Capture Verification Visit Form |  | 
    await driver.findElement(By.linkText("Capture Verification Visit Form")).click()
    // 136 | click | id=psi_site_visit848 |  | 
    await driver.findElement(By.id("psi_site_visit848")).click()
    // 137 | type | id=psi_site_visit848 | 2021-12-15 | 
    await driver.findElement(By.id("psi_site_visit848")).sendKeys("2021-12-15")
    // 138 | click | name=member[name][] |  | 
    await driver.findElement(By.name("member[name][]")).click()
    // 139 | type | name=member[name][] | Andrew Garfield | 
    await driver.findElement(By.name("member[name][]")).sendKeys("Andrew Garfield")
    // 140 | click | name=member[role][] |  | 
    await driver.findElement(By.name("member[role][]")).click()
    // 141 | click | name=member[role][] |  | 
    await driver.findElement(By.name("member[role][]")).click()
    // 142 | click | id=more-v |  | 
    await driver.findElement(By.id("more-v")).click()
    // 143 | mouseOver | id=more-v |  | 
    {
      const element = await driver.findElement(By.id("more-v"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 144 | mouseOut | id=more-v |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 145 | click | css=.row:nth-child(3) > .col-md-6 > .form-control |  | 
    await driver.findElement(By.css(".row:nth-child(3) > .col-md-6 > .form-control")).click()
    // 146 | type | css=.row:nth-child(3) > .col-md-6 > .form-control | David Messar | 
    await driver.findElement(By.css(".row:nth-child(3) > .col-md-6 > .form-control")).sendKeys("David Messar")
    // 147 | click | css=.row:nth-child(3) > .col-md-5 > .form-control |  | 
    await driver.findElement(By.css(".row:nth-child(3) > .col-md-5 > .form-control")).click()
    // 148 | select | css=.row:nth-child(3) > .col-md-5 > .form-control | label=Desk Officer | 
    {
      const dropdown = await driver.findElement(By.css(".row:nth-child(3) > .col-md-5 > .form-control"))
      await dropdown.findElement(By.xpath("//option[. = 'Desk Officer']")).click()
    }
    // 149 | click | id=more-v |  | 
    await driver.findElement(By.id("more-v")).click()
    // 150 | mouseOver | id=more-v |  | 
    {
      const element = await driver.findElement(By.id("more-v"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 151 | mouseOut | id=more-v |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 152 | click | css=.row:nth-child(5) > .col-md-6 > .form-control |  | 
    await driver.findElement(By.css(".row:nth-child(5) > .col-md-6 > .form-control")).click()
    // 153 | type | css=.row:nth-child(5) > .col-md-6 > .form-control | John Doe | 
    await driver.findElement(By.css(".row:nth-child(5) > .col-md-6 > .form-control")).sendKeys("John Doe")
    // 154 | click | css=.row:nth-child(5) > .col-md-5 > .form-control |  | 
    await driver.findElement(By.css(".row:nth-child(5) > .col-md-5 > .form-control")).click()
    // 155 | select | css=.row:nth-child(5) > .col-md-5 > .form-control | label=Team Member | 
    {
      const dropdown = await driver.findElement(By.css(".row:nth-child(5) > .col-md-5 > .form-control"))
      await dropdown.findElement(By.xpath("//option[. = 'Team Member']")).click()
    }
    // 156 | click | css=.btn:nth-child(22) |  | 
    await driver.findElement(By.css(".btn:nth-child(22)")).click()
    // 157 | click | id=modal-popup-close |  | 
    await driver.findElement(By.id("modal-popup-close")).click()
    // 158 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 159 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 160 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 161 | type | name=nwp_wf_comment | Okay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Okay")
    // 162 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 163 | mouseOver | css=.col-md-12 > .btn |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 164 | mouseOut | css=.processing-ajax-request |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 165 | click | css=.row_selected > td:nth-child(6) |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(6)")).click()
    // 166 | click | css=.odd:nth-child(1) > td:nth-child(5) |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(5)")).click()
    // 167 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 168 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 169 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 170 | type | name=nwp_wf_comment | OKay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("OKay")
    // 171 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 172 | click | css=.row_selected > td:nth-child(5) |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(5)")).click()
    // 173 | click | css=.odd:nth-child(1) > td:nth-child(6) > b |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(6) > b")).click()
    // 174 | click | id=dynamic |  | 
    await driver.findElement(By.id("dynamic")).click()
    // 175 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 176 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 177 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 178 | type | name=nwp_wf_comment | Okay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Okay")
    // 179 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 180 | click | name=file |  | 
    await driver.findElement(By.name("file")).click()
    // 181 | click | css=.form-group |  | 
    await driver.findElement(By.css(".form-group")).click()
    // 182 | click | css=.remove-uploaded-file |  | 
    await driver.findElement(By.css(".remove-uploaded-file")).click()
    // 183 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 184 | mouseOver | css=.col-md-12 > .btn |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 185 | mouseOut | css=.col-md-12 > .btn |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 186 | click | id=modal-popup-close |  | 
    await driver.findElement(By.id("modal-popup-close")).click()
    // 187 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 188 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 189 | mouseOver | linkText=Approve |  | 
    {
      const element = await driver.findElement(By.linkText("Approve"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 190 | mouseOut | css=.btn-group:nth-child(2) li:nth-child(1) > .custom-single-selected-record-button |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 191 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 192 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 193 | type | name=nwp_wf_comment | okay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("okay")
    // 194 | click | css=.row:nth-child(14) > .col-md-12 |  | 
    await driver.findElement(By.css(".row:nth-child(14) > .col-md-12")).click()
    // 195 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 196 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 197 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 198 | mouseOver | css=.col-md-12 > .btn |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 199 | mouseOut | css=.processing-ajax-request |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 200 | mouseOver | css=.remove-uploaded-file |  | 
    {
      const element = await driver.findElement(By.css(".remove-uploaded-file"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 201 | click | name=file |  | 
    await driver.findElement(By.name("file")).click()
    // 202 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 203 | mouseOver | css=.col-md-12 > .btn |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 204 | mouseOut | css=.processing-ajax-request |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 205 | click | css=.row_selected > td:nth-child(5) |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(5)")).click()
    // 206 | click | css=.odd:nth-child(1) > td:nth-child(5) |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(5)")).click()
    // 207 | doubleClick | css=.row_selected > td:nth-child(5) |  | 
    {
      const element = await driver.findElement(By.css(".row_selected > td:nth-child(5)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 208 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 209 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 210 | mouseOver | linkText=Approve |  | 
    {
      const element = await driver.findElement(By.linkText("Approve"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 211 | mouseOut | css=.btn-group:nth-child(2) li:nth-child(1) > .custom-single-selected-record-button |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 212 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 213 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 214 | mouseOver | linkText=Approve |  | 
    {
      const element = await driver.findElement(By.linkText("Approve"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 215 | mouseOut | css=.btn-group:nth-child(2) li:nth-child(1) > .custom-single-selected-record-button |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 216 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 217 | click | linkText=Appoint/Approve Visitation Date |  | 
    await driver.findElement(By.linkText("Appoint/Approve Visitation Date")).click()
    // 218 | click | id=form-gen-submit |  | 
    await driver.findElement(By.id("form-gen-submit")).click()
    // 219 | mouseOver | id=form-gen-submit |  | 
    {
      const element = await driver.findElement(By.id("form-gen-submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 220 | mouseOut | id=form-gen-submit |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 221 | click | id=modal-popup-close |  | 
    await driver.findElement(By.id("modal-popup-close")).click()
    // 222 | click | id=dynamic |  | 
    await driver.findElement(By.id("dynamic")).click()
    // 223 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 224 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 225 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 226 | type | name=nwp_wf_comment | Okay | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Okay")
    // 227 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 228 | click | css=.row_selected > td:nth-child(6) > b |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(6) > b")).click()
    // 229 | click | css=.odd:nth-child(1) > td:nth-child(6) > b |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(6) > b")).click()
    // 230 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 231 | click | linkText=Approve |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 232 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 233 | click | linkText=New Site Visit Report |  | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 234 | storeWindowHandle | root |  | 
    await driver.findElement(By.linkText("New Site Visit Report")).click()
    // 235 | selectWindow | handle=${win9553} |  | 
    vars["win9553"] = await waitForWindow(2000)
    // 236 | click | css=li:nth-child(2) span |  | 
    vars["root"] = await driver.getWindowHandle()
    // 237 | click | linkText=Verification Visit |  | 
    await driver.switchTo().window(vars["win9553"])
    // 238 | click | css=.btn |  | 
    await driver.findElement(By.css("li:nth-child(2) span")).click()
    // 239 | mouseOver | css=.btn |  | 
    await driver.findElement(By.linkText("Verification Visit")).click()
    // 240 | click | id=psi_verification_criteria853 |  | 
    await driver.findElement(By.css(".btn")).click()
    // 241 | type | id=psi_verification_criteria853 | 2021-12-12 | 
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 242 | click | id=psi_verification_criteria914 |  | 
    await driver.findElement(By.id("psi_verification_criteria853")).click()
    // 243 | select | id=psi_verification_criteria914 | label=No | 
    await driver.findElement(By.id("psi_verification_criteria853")).sendKeys("2021-12-12")
    // 244 | click | name=owners[name][] |  | 
    await driver.findElement(By.id("psi_verification_criteria914")).click()
    // 245 | type | name=owners[name][] | John Doe | 
    {
      const dropdown = await driver.findElement(By.id("psi_verification_criteria914"))
      await dropdown.findElement(By.xpath("//option[. = 'No']")).click()
    }
    // 246 | type | name=owners[email][] | john.doe@hotmail.com | 
    await driver.findElement(By.name("owners[name][]")).click()
    // 247 | type | name=owners[phone][] | +6052492183 | 
    await driver.findElement(By.name("owners[name][]")).sendKeys("John Doe")
    // 248 | click | name=owners[designation][] |  | 
    await driver.findElement(By.name("owners[email][]")).sendKeys("john.doe@hotmail.com")
    // 249 | type | name=owners[designation][] | Mr | 
    await driver.findElement(By.name("owners[phone][]")).sendKeys("+6052492183")
    // 250 | click | id=psi_verification_criteria854 |  | 
    await driver.findElement(By.name("owners[designation][]")).click()
    // 251 | chooseCancelOnNextPrompt |  |  | 
    await driver.findElement(By.name("owners[designation][]")).sendKeys("Mr")
    // 252 | assertPrompt | Open File Directory |  | 
    await driver.findElement(By.id("psi_verification_criteria854")).click()
    // 254 | chooseCancelOnNextPrompt |  |  | 
    assert(await driver.switchTo().alert().getText() == "Open File Directory")
    // 255 | assertPrompt | Open File Directory |  | 
    await driver.switchTo().alert().dismiss()
    // 257 | type | id=psi_verification_criteria854 | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    assert(await driver.switchTo().alert().getText() == "Open File Directory")
    // 258 | type | id=psi_verification_criteria854 | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.switchTo().alert().dismiss()
    // 259 | click | id=psi_verification_criteria855 |  | 
    await driver.findElement(By.id("psi_verification_criteria854")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 260 | type | id=psi_verification_criteria855 | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.id("psi_verification_criteria854")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 261 | click | name=submit |  | 
    await driver.findElement(By.id("psi_verification_criteria855")).click()
    // 262 | mouseOver | name=submit |  | 
    await driver.findElement(By.id("psi_verification_criteria855")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 263 | click | name=product[name][] |  | 
    await driver.findElement(By.name("submit")).click()
    // 264 | type | name=product[name][] | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    {
      const element = await driver.findElement(By.name("submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 265 | click | id=more-products |  | 
    await driver.findElement(By.name("product[name][]")).click()
    // 266 | mouseOver | id=more-products |  | 
    await driver.findElement(By.name("product[name][]")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 267 | mouseOut | id=more-products |  | 
    await driver.findElement(By.id("more-products")).click()
    // 268 | click | css=.row:nth-child(2) > .col-md-6 > .form-control |  | 
    {
      const element = await driver.findElement(By.id("more-products"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 269 | chooseCancelOnNextPrompt |  |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 270 | assertPrompt | Open File Directory |  | 
    await driver.findElement(By.css(".row:nth-child(2) > .col-md-6 > .form-control")).click()
    // 272 | type | css=.row:nth-child(2) > .col-md-6 > .form-control | Quasi qui facilis natus distinctio voluptatem vel error. | 
    assert(await driver.switchTo().alert().getText() == "Open File Directory")
    // 273 | type | css=.row:nth-child(2) > .col-md-6 > .form-control | Quasi qui facilis natus distinctio voluptatem vel error. | 
    await driver.switchTo().alert().dismiss()
    // 274 | click | id=more-products |  | 
    await driver.findElement(By.css(".row:nth-child(2) > .col-md-6 > .form-control")).sendKeys("Quasi qui facilis natus distinctio voluptatem vel error.")
    // 275 | mouseOver | id=more-products |  | 
    await driver.findElement(By.css(".row:nth-child(2) > .col-md-6 > .form-control")).sendKeys("Quasi qui facilis natus distinctio voluptatem vel error.")
    // 276 | mouseOut | id=more-products |  | 
    await driver.findElement(By.id("more-products")).click()
    // 277 | chooseCancelOnNextPrompt |  |  | 
    {
      const element = await driver.findElement(By.id("more-products"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 278 | assertPrompt | Open File Directory |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 280 | type | css=.row:nth-child(3) > .col-md-6 > .form-control | ea ut similique | 
    assert(await driver.switchTo().alert().getText() == "Open File Directory")
    // 281 | type | css=.row:nth-child(3) > .col-md-6 > .form-control | ea ut similique | 
    await driver.switchTo().alert().dismiss()
    // 282 | click | css=.psi_verification_criteria856-row .form-check:nth-child(1) > .form-check-label |  | 
    await driver.findElement(By.css(".row:nth-child(3) > .col-md-6 > .form-control")).sendKeys("ea ut similique")
    // 283 | click | css=.psi_verification_criteria857-row .form-check:nth-child(2) > .form-check-label |  | 
    await driver.findElement(By.css(".row:nth-child(3) > .col-md-6 > .form-control")).sendKeys("ea ut similique")
    // 284 | click | css=.psi_verification_criteria858-row .form-check:nth-child(3) |  | 
    await driver.findElement(By.css(".psi_verification_criteria856-row .form-check:nth-child(1) > .form-check-label")).click()
    // 285 | click | css=.psi_verification_criteria858-row .form-check:nth-child(3) |  | 
    await driver.findElement(By.css(".psi_verification_criteria857-row .form-check:nth-child(2) > .form-check-label")).click()
    // 286 | click | css=.psi_verification_criteria858-row .form-check:nth-child(3) > .form-check-label |  | 
    await driver.findElement(By.css(".psi_verification_criteria858-row .form-check:nth-child(3)")).click()
    // 287 | click | css=.psi_verification_criteria859-row .form-check:nth-child(4) > .form-check-label |  | 
    await driver.findElement(By.css(".psi_verification_criteria858-row .form-check:nth-child(3)")).click()
    // 288 | click | name=submit |  | 
    await driver.findElement(By.css(".psi_verification_criteria858-row .form-check:nth-child(3) > .form-check-label")).click()
    // 289 | mouseOver | name=submit |  | 
    await driver.findElement(By.css(".psi_verification_criteria859-row .form-check:nth-child(4) > .form-check-label")).click()
    // 290 | click | name=data[raw_mat][] |  | 
    await driver.findElement(By.name("submit")).click()
    // 291 | type | name=data[raw_mat][] | Rice( 2 Bags ) | 
    {
      const element = await driver.findElement(By.name("submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 292 | click | name=data[import_plans][] |  | 
    await driver.findElement(By.name("data[raw_mat][]")).click()
    // 293 | chooseCancelOnNextPrompt |  |  | 
    await driver.findElement(By.name("data[raw_mat][]")).sendKeys("Rice( 2 Bags )")
    // 294 | assertPrompt | Open File Directory |  | 
    await driver.findElement(By.name("data[import_plans][]")).click()
    // 296 | type | name=data[import_plans][] | Rerum in non qui ipsum saepe inventore. Omnis odit cupiditate aliquid nihil recusandae ea cum ullam. Minima dolorum provident unde facilis cumque aut. Amet nobis aut. Quo veritatis quo molestiae qui cumque quasi qui sit. Neque esse eveniet delectus dolores autem. | 
    assert(await driver.switchTo().alert().getText() == "Open File Directory")
    // 297 | type | name=data[import_plans][] | Rerum in non qui ipsum saepe inventore. Omnis odit cupiditate aliquid nihil recusandae ea cum ullam. Minima dolorum provident unde facilis cumque aut. Amet nobis aut. Quo veritatis quo molestiae qui cumque quasi qui sit. Neque esse eveniet delectus dolores autem. | 
    await driver.switchTo().alert().dismiss()
    // 298 | click | css=.btn-primary |  | 
    await driver.findElement(By.name("data[import_plans][]")).sendKeys("Rerum in non qui ipsum saepe inventore. Omnis odit cupiditate aliquid nihil recusandae ea cum ullam. Minima dolorum provident unde facilis cumque aut. Amet nobis aut. Quo veritatis quo molestiae qui cumque quasi qui sit. Neque esse eveniet delectus dolores autem.")
    // 299 | click | name=data[power][description] |  | 
    await driver.findElement(By.name("data[import_plans][]")).sendKeys("Rerum in non qui ipsum saepe inventore. Omnis odit cupiditate aliquid nihil recusandae ea cum ullam. Minima dolorum provident unde facilis cumque aut. Amet nobis aut. Quo veritatis quo molestiae qui cumque quasi qui sit. Neque esse eveniet delectus dolores autem.")
    // 300 | chooseCancelOnNextPrompt |  |  | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 301 | assertPrompt | Open File Directory |  | 
    await driver.findElement(By.name("data[power][description]")).click()
    // 303 | type | name=data[power][description] | Aut quia provident laudantium id asperiores laboriosam voluptates ut. Eveniet et nobis labore fugit temporibus. Ut numquam est consequuntur est autem ipsa quod voluptatibus. At ut minus nam impedit non sint vel. Fuga voluptate sit voluptatem explicabo quis et enim eaque. | 
    assert(await driver.switchTo().alert().getText() == "Open File Directory")
    // 304 | click | name=data[power][description] |  | 
    await driver.switchTo().alert().dismiss()
    // 305 | type | name=data[power][description] | Aut quia provident laudantium id asperiores laboriosam voluptates ut. Eveniet et nobis labore fugit temporibus. Ut numquam est consequuntur est autem ipsa quod voluptatibus. At ut minus nam impedit non sint vel. Fuga voluptate sit voluptatem explicabo quis et enim eaque. | 
    await driver.findElement(By.name("data[power][description]")).sendKeys("Aut quia provident laudantium id asperiores laboriosam voluptates ut. Eveniet et nobis labore fugit temporibus. Ut numquam est consequuntur est autem ipsa quod voluptatibus. At ut minus nam impedit non sint vel. Fuga voluptate sit voluptatem explicabo quis et enim eaque.")
    // 306 | chooseCancelOnNextPrompt |  |  | 
    await driver.findElement(By.name("data[power][description]")).click()
    // 307 | assertPrompt | Open File Directory |  | 
    await driver.findElement(By.name("data[power][description]")).sendKeys("Aut quia provident laudantium id asperiores laboriosam voluptates ut. Eveniet et nobis labore fugit temporibus. Ut numquam est consequuntur est autem ipsa quod voluptatibus. At ut minus nam impedit non sint vel. Fuga voluptate sit voluptatem explicabo quis et enim eaque.")
    // 309 | type | name=data[power][location] | 5006 Dedric Shores | 
    assert(await driver.switchTo().alert().getText() == "Open File Directory")
    // 310 | type | name=data[power][location] | 5006 Dedric Shores | 
    await driver.switchTo().alert().dismiss()
    // 311 | click | name=data[water][description] |  | 
    await driver.findElement(By.name("data[power][location]")).sendKeys("5006 Dedric Shores")
    // 312 | click | name=data[power][description] |  | 
    await driver.findElement(By.name("data[power][location]")).sendKeys("5006 Dedric Shores")
    // 313 | click | name=data[water][description] |  | 
    await driver.findElement(By.name("data[water][description]")).click()
    // 314 | type | name=data[water][description] | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.name("data[power][description]")).click()
    // 315 | click | name=data[road][description] |  | 
    await driver.findElement(By.name("data[water][description]")).click()
    // 316 | type | name=data[road][description] | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.name("data[water][description]")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 317 | click | name=data[other][description] |  | 
    await driver.findElement(By.name("data[road][description]")).click()
    // 318 | type | name=data[other][description] | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.name("data[road][description]")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 319 | click | name=data[water][location] |  | 
    await driver.findElement(By.name("data[other][description]")).click()
    // 320 | type | name=data[water][location] | FCT | 
    await driver.findElement(By.name("data[other][description]")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 321 | click | name=data[water][quality] |  | 
    await driver.findElement(By.name("data[water][location]")).click()
    // 322 | select | name=data[water][quality] | label=Good | 
    await driver.findElement(By.name("data[water][location]")).sendKeys("FCT")
    // 323 | click | name=data[road][location] |  | 
    await driver.findElement(By.name("data[water][quality]")).click()
    // 324 | type | name=data[road][location] | Kwara | 
    {
      const dropdown = await driver.findElement(By.name("data[water][quality]"))
      await dropdown.findElement(By.xpath("//option[. = 'Good']")).click()
    }
    // 325 | click | name=data[road][quality] |  | 
    await driver.findElement(By.name("data[road][location]")).click()
    // 326 | select | name=data[road][quality] | label=Fair | 
    await driver.findElement(By.name("data[road][location]")).sendKeys("Kwara")
    // 327 | click | name=data[other][location] |  | 
    await driver.findElement(By.name("data[road][quality]")).click()
    // 328 | type | name=data[other][location] | By the lake | 
    {
      const dropdown = await driver.findElement(By.name("data[road][quality]"))
      await dropdown.findElement(By.xpath("//option[. = 'Fair']")).click()
    }
    // 329 | click | id=psi_verification_criteria860 |  | 
    await driver.findElement(By.name("data[other][location]")).click()
    // 330 | type | id=psi_verification_criteria860 | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.name("data[other][location]")).sendKeys("By the lake")
    // 331 | click | id=psi_verification_criteria861 |  | 
    await driver.findElement(By.id("psi_verification_criteria860")).click()
    // 332 | type | id=psi_verification_criteria861 | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.id("psi_verification_criteria860")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 333 | click | css=.btn |  | 
    await driver.findElement(By.id("psi_verification_criteria861")).click()
    // 334 | click | id=form-gen-submit |  | 
    await driver.findElement(By.id("psi_verification_criteria861")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 335 | click | id=psi_verification_criteria862 |  | 
    await driver.findElement(By.css(".btn")).click()
    // 336 | type | id=psi_verification_criteria862 | Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus est at eum nihil eius nostrum quibusdam, asperiores, tenetur. Dolores saepe minus molestias cumque, quo qui tempore vero itaque, fug | 
    await driver.findElement(By.id("form-gen-submit")).click()
    // 337 | click | id=psi_verification_criteria863 |  | 
    await driver.findElement(By.id("psi_verification_criteria862")).click()
    // 338 | type | id=psi_verification_criteria863 | Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus est at eum nihil eius nostrum quibusdam, asperiores, tenetur. Dolores saepe minus molestias cumque, quo qui tempore vero itaque, fug | 
    await driver.findElement(By.id("psi_verification_criteria862")).sendKeys("Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus est at eum nihil eius nostrum quibusdam, asperiores, tenetur. Dolores saepe minus molestias cumque, quo qui tempore vero itaque, fug")
    // 339 | click | id=psi_verification_criteria864 |  | 
    await driver.findElement(By.id("psi_verification_criteria863")).click()
    // 340 | type | id=psi_verification_criteria864 | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.id("psi_verification_criteria863")).sendKeys("Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusamus est at eum nihil eius nostrum quibusdam, asperiores, tenetur. Dolores saepe minus molestias cumque, quo qui tempore vero itaque, fug")
    // 341 | click | css=.btn |  | 
    await driver.findElement(By.id("psi_verification_criteria864")).click()
    // 342 | mouseOver | css=.btn |  | 
    await driver.findElement(By.id("psi_verification_criteria864")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 343 | mouseOut | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 344 | click | name=data[training_program][] |  | 
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 345 | type | name=data[training_program][] | By No Means | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 346 | click | name=data[number_trained][] |  | 
    await driver.findElement(By.name("data[training_program][]")).click()
    // 347 | type | name=data[number_trained][] | 23 | 
    await driver.findElement(By.name("data[training_program][]")).sendKeys("By No Means")
    // 348 | click | name=data[comment][] |  | 
    await driver.findElement(By.name("data[number_trained][]")).click()
    // 349 | type | name=data[comment][] | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.name("data[number_trained][]")).sendKeys("23")
    // 350 | click | css=.btn-primary |  | 
    await driver.findElement(By.name("data[comment][]")).click()
    // 351 | mouseOver | css=.btn-primary |  | 
    await driver.findElement(By.name("data[comment][]")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 352 | click | id=psi_verification_criteria865 |  | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 353 | select | id=psi_verification_criteria865 | label=No | 
    {
      const element = await driver.findElement(By.css(".btn-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 354 | click | id=psi_verification_criteria867 |  | 
    await driver.findElement(By.id("psi_verification_criteria865")).click()
    // 355 | type | id=psi_verification_criteria867 | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    {
      const dropdown = await driver.findElement(By.id("psi_verification_criteria865"))
      await dropdown.findElement(By.xpath("//option[. = 'No']")).click()
    }
    // 356 | click | id=psi_verification_criteria868 |  | 
    await driver.findElement(By.id("psi_verification_criteria867")).click()
    // 357 | type | id=psi_verification_criteria868 | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.id("psi_verification_criteria867")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 358 | click | css=.btn-primary |  | 
    await driver.findElement(By.id("psi_verification_criteria868")).click()
    // 359 | mouseOver | css=.btn-primary |  | 
    await driver.findElement(By.id("psi_verification_criteria868")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 360 | mouseOut | css=.btn-primary |  | 
    await driver.findElement(By.css(".btn-primary")).click()
    // 361 | click | name=submit |  | 
    {
      const element = await driver.findElement(By.css(".btn-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 362 | click | css=.finish-btn |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 363 | click | css=.btn |  | 
    await driver.findElement(By.name("submit")).click()
    // 364 | chooseOkOnNextConfirmation |  |  | 
    await driver.findElement(By.css(".finish-btn")).click()
    // 365 | assertConfirmation | Are you sure you want to submit this form? |  | 
    await driver.findElement(By.css(".btn")).click()
    // 367 | selectWindow | handle=${root} |  | 
    assert(await driver.switchTo().alert().getText() == "Are you sure you want to submit this form?")
    // 368 | click | linkText=More |  | 
    await driver.switchTo().alert().accept()
    // 369 | click | linkText=Approve |  | 
    await driver.switchTo().window(vars["root"])
    // 370 | click | css=.vertical-nav-menu > .app-sidebar__heading:nth-child(13) |  | 
    await driver.findElement(By.linkText("More")).click()
    // 371 | click | css=.app-sidebar__heading:nth-child(19) |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 372 | click | linkText=Verification Visit |  | 
    await driver.findElement(By.css(".vertical-nav-menu > .app-sidebar__heading:nth-child(13)")).click()
    // 373 | mouseOver | linkText=Verification Visit |  | 
    await driver.findElement(By.css(".app-sidebar__heading:nth-child(19)")).click()
    // 374 | mouseOut | linkText=Verification Visit |  | 
    await driver.findElement(By.linkText("Verification Visit")).click()
    // 375 | click | css=.odd:nth-child(1) > td:nth-child(5) |  | 
    {
      const element = await driver.findElement(By.linkText("Verification Visit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 376 | click | linkText=Actions |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 377 | click | linkText=Approve |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(5)")).click()
    // 378 | mouseOver | linkText=Approve |  | 
    await driver.findElement(By.linkText("Actions")).click()
    // 379 | mouseOut | css=.hyella-source-container:nth-child(3) > .btn-group li:nth-child(1) > .custom-single-selected-record-button |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 380 | click | css=.app-sidebar__heading:nth-child(1) |  | 
    {
      const element = await driver.findElement(By.linkText("Approve"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 381 | click | linkText=Approvals |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 382 | click | linkText=View All |  | 
    await driver.findElement(By.css(".app-sidebar__heading:nth-child(1)")).click()
    // 383 | click | css=.odd:nth-child(1) > td:nth-child(5) |  | 
    await driver.findElement(By.linkText("Approvals")).click()
    // 384 | click | linkText=More |  | 
    await driver.findElement(By.linkText("View All")).click()
    // 385 | click | linkText=Approve |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(5)")).click()
    // 386 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.linkText("More")).click()
    // 387 | type | name=nwp_wf_comment | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.linkText("Approve")).click()
    // 388 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 389 | mouseOver | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 390 | mouseOut | css=.processing-ajax-request |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 391 | click | css=.row_selected > td:nth-child(6) > b |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 392 | click | css=.odd:nth-child(1) > td:nth-child(6) > b |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 393 | doubleClick | css=.row_selected > td:nth-child(6) > b |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(6) > b")).click()
    // 394 | click | linkText=More |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(6) > b")).click()
    // 395 | click | linkText=Approve |  | 
    {
      const element = await driver.findElement(By.css(".row_selected > td:nth-child(6) > b"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    // 396 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.linkText("More")).click()
    // 397 | type | name=nwp_wf_comment | Okay | 
    await driver.findElement(By.linkText("Approve")).click()
    // 398 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 399 | mouseOver | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Okay")
    // 400 | mouseOut | css=.processing-ajax-request |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 401 | click | css=.row_selected > td:nth-child(6) > b |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 402 | click | css=.odd:nth-child(1) > td:nth-child(6) > b |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 403 | click | linkText=More |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(6) > b")).click()
    // 404 | click | linkText=View Site Visit Report |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(6) > b")).click()
    // 405 | click | css=.close > .icon-remove |  | 
    await driver.findElement(By.linkText("More")).click()
    // 406 | click | linkText=More |  | 
    await driver.findElement(By.linkText("View Site Visit Report")).click()
    // 407 | click | linkText=View Site Visit Report |  | 
    await driver.findElement(By.css(".close > .icon-remove")).click()
    // 408 | click | id=modal-popup-close |  | 
    await driver.findElement(By.linkText("More")).click()
    // 409 | click | linkText=More |  | 
    await driver.findElement(By.linkText("View Site Visit Report")).click()
    // 410 | click | linkText=Approve |  | 
    await driver.findElement(By.id("modal-popup-close")).click()
    // 411 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.linkText("More")).click()
    // 412 | type | name=nwp_wf_comment | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.linkText("Approve")).click()
    // 413 | click | name=nwp_wf_next_state |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 414 | select | name=nwp_wf_next_state | label=SERVICE CHARGE INVOICE | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 415 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.name("nwp_wf_next_state")).click()
    // 416 | click | css=.row_selected > td:nth-child(6) |  | 
    {
      const dropdown = await driver.findElement(By.name("nwp_wf_next_state"))
      await dropdown.findElement(By.xpath("//option[. = 'SERVICE CHARGE INVOICE']")).click()
    }
    // 417 | click | css=.odd:nth-child(1) > td:nth-child(6) |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 418 | click | linkText=More |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(6)")).click()
    // 419 | click | linkText=Approve |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(6)")).click()
    // 420 | click | linkText=More |  | 
    await driver.findElement(By.linkText("More")).click()
    // 421 | click | linkText=Confirm Payment |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 422 | click | css=.odd:nth-child(1) > td:nth-child(5) |  | 
    await driver.findElement(By.linkText("More")).click()
    // 423 | click | linkText=Confirm Payment |  | 
    await driver.findElement(By.linkText("Confirm Payment")).click()
    // 424 | mouseOver | linkText=Confirm Payment |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(5)")).click()
    // 425 | mouseOut | linkText=Confirm Payment |  | 
    await driver.findElement(By.linkText("Confirm Payment")).click()
    // 426 | click | id=eosic_payments396 |  | 
    {
      const element = await driver.findElement(By.linkText("Confirm Payment"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 427 | type | id=eosic_payments396 | 788000 | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 428 | click | id=eosic_payments145 |  | 
    await driver.findElement(By.id("eosic_payments396")).click()
    // 429 | type | id=eosic_payments145 | 8941548954 | 
    await driver.findElement(By.id("eosic_payments396")).sendKeys("788000")
    // 430 | click | id=form-gen-submit |  | 
    await driver.findElement(By.id("eosic_payments145")).click()
    // 431 | mouseOver | id=form-gen-submit |  | 
    await driver.findElement(By.id("eosic_payments145")).sendKeys("8941548954")
    // 432 | click | id=modal-popup-close |  | 
    await driver.findElement(By.id("form-gen-submit")).click()
    // 433 | click | linkText=Approval Dashboard |  | 
    {
      const element = await driver.findElement(By.id("form-gen-submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 434 | click | id=tab2-handle |  | 
    await driver.findElement(By.id("modal-popup-close")).click()
    // 435 | click | css=.odd:nth-child(1) > td:nth-child(5) |  | 
    await driver.findElement(By.linkText("Approval Dashboard")).click()
    // 436 | click | linkText=More |  | 
    await driver.findElement(By.id("tab2-handle")).click()
    // 437 | click | linkText=Approve |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(5)")).click()
    // 438 | mouseOver | linkText=Approve |  | 
    await driver.findElement(By.linkText("More")).click()
    // 439 | mouseOut | css=.btn-group:nth-child(2) li:nth-child(1) > .custom-single-selected-record-button |  | 
    await driver.findElement(By.linkText("Approve")).click()
    // 440 | click | name=nwp_wf_comment |  | 
    {
      const element = await driver.findElement(By.linkText("Approve"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 441 | type | name=nwp_wf_comment | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 442 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 443 | mouseOver | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 444 | mouseOut | css=.processing-ajax-request |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 445 | click | css=.row_selected > td:nth-child(6) |  | 
    {
      const element = await driver.findElement(By.css(".col-md-12 > .btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 446 | click | css=.odd:nth-child(1) > td:nth-child(6) |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 447 | click | linkText=More |  | 
    await driver.findElement(By.css(".row_selected > td:nth-child(6)")).click()
    // 448 | click | linkText=Approve |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(6)")).click()
    // 449 | click | name=nwp_wf_comment |  | 
    await driver.findElement(By.linkText("More")).click()
    // 450 | type | name=nwp_wf_comment | Tenetur veritatis sed ullam enim porro rerum occaecati sunt. | 
    await driver.findElement(By.linkText("Approve")).click()
    // 451 | click | css=.col-md-12 > .btn |  | 
    await driver.findElement(By.name("nwp_wf_comment")).click()
    // 452 | chooseOkOnNextConfirmation |  |  | 
    await driver.findElement(By.name("nwp_wf_comment")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    // 453 | assertConfirmation | Are you sure you want to submit this form? |  | 
    await driver.findElement(By.css(".col-md-12 > .btn")).click()
    // 455 | click | css=.vertical-nav-menu > .app-sidebar__heading:nth-child(13) |  | 
    assert(await driver.switchTo().alert().getText() == "Are you sure you want to submit this form?")
    // 456 | click | css=li:nth-child(14) .app-sidebar__heading:nth-child(9) |  | 
    await driver.switchTo().alert().accept()
    // 457 | click | linkText=Approved |  | 
    await driver.findElement(By.css(".vertical-nav-menu > .app-sidebar__heading:nth-child(13)")).click()
    // 458 | click | css=.odd:nth-child(1) > td:nth-child(4) |  | 
    await driver.findElement(By.css("li:nth-child(14) .app-sidebar__heading:nth-child(9)")).click()
    // 459 | click | linkText=Actions |  | 
    await driver.findElement(By.linkText("Approved")).click()
    // 460 | click | linkText=View Certificate |  | 
    await driver.findElement(By.css(".odd:nth-child(1) > td:nth-child(4)")).click()
    // 461 | mouseOver | linkText=View Certificate |  | 
    await driver.findElement(By.linkText("Actions")).click()
    // 462 | mouseOut | css=.hyella-source-container:nth-child(3) > .btn-group li:nth-child(3) > .custom-single-selected-record-button |  | 
    await driver.findElement(By.linkText("View Certificate")).click()
    // 463 | click | id=modal-popup-close |  | 
    {
      const element = await driver.findElement(By.linkText("View Certificate"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 464 | click | linkText=Actions |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 465 | click | linkText=Open |  | 
    await driver.findElement(By.id("modal-popup-close")).click()
    // 466 | mouseOver | linkText=Open |  | 
    await driver.findElement(By.linkText("Actions")).click()
    // 467 | mouseOut | css=.hyella-source-container:nth-child(3) > .btn-group li:nth-child(1) > .custom-single-selected-record-button |  | 
    await driver.findElement(By.linkText("Open")).click()
    // 468 | click | linkText=View Business Info |  | 
    {
      const element = await driver.findElement(By.linkText("Open"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 469 | click | linkText=Approved |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 470 | mouseOver | linkText=Queried |  | 
    await driver.findElement(By.linkText("View Business Info")).click()
    // 471 | mouseOut | linkText=Queried |  | 
    await driver.findElement(By.linkText("Approved")).click()
    // 472 | click | css=.fa-angle-down |  | 
    {
      const element = await driver.findElement(By.linkText("Queried"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 473 | click | id=sign-out-dp |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 474 | close |  |  | 
    await driver.findElement(By.css(".fa-angle-down")).click()
    // 475 | selectWindow | handle=${win9553} |  | 
    await driver.findElement(By.id("sign-out-dp")).click()
    // 476 | click | css=.sidebar |  | 
    await driver.close()
    // 477 | close |  |  | 
    await driver.switchTo().window(vars["win9553"])
    // 478 | //click | linkText=Confirm Payment |  | 
    await driver.findElement(By.css(".sidebar")).click()
    await driver.close()
  })
})
