// Generated by Selenium IDE
const { Builder, By } = require('selenium-webdriver')

describe('IOP Login and Resume Registration', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('IOP Login and Resume Registration', async function() {
    // Test name: IOP Login and Resume Registration
    // Step # | name | target | value
    // 1 | open | http://localhost:819/solutions/nipc/ | 
    // await driver.get("http://localhost:819/solutions/nipc/")
    await driver.get(config[ config.env ].url);
    // 2 | setWindowSize | 951x864 | 
    await driver.manage().window().setRect({ width: 951, height: 864 })
    // 3 | click | linkText=Sign In | 
    await driver.findElement(By.linkText("Sign In")).click()
    // 4 | click | css=.submit-border > input | 
    await driver.findElement(By.css(".submit-border > input")).click()
    // 5 | click | css=.list-group-item-action:nth-child(3) | 
    await driver.findElement(By.css(".list-group-item-action:nth-child(3)")).click()
    // 6 | click | css=tr:nth-child(2) .custom-single-selected-record-button | 
    await driver.findElement(By.css("tr:nth-child(2) .custom-single-selected-record-button")).click()
    // 7 | click | id=sub-menu-b_biz | 
    await driver.findElement(By.id("sub-menu-b_biz")).click()
    // 8 | mouseOver | id=sub-menu-b_biz | 
    {
      const element = await driver.findElement(By.id("sub-menu-b_biz"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 9 | mouseOut | id=sub-menu-b_biz | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 10 | mouseOver | css=.select2-chosen | 
    {
      const element = await driver.findElement(By.css(".select2-chosen"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 11 | mouseOut | css=.select2-chosen | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 12 | mouseDown | css=.select2-chosen | 
    {
      const element = await driver.findElement(By.css(".select2-chosen"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 13 | mouseUp | id=select2-drop-mask | 
    {
      const element = await driver.findElement(By.id("select2-drop-mask"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 14 | click | css=body | 
    await driver.findElement(By.css("body")).click()
    // 15 | click | css=.select2-choices | 
    await driver.findElement(By.css(".select2-choices")).click()
    // 16 | click | id=form-gen-submit | 
    await driver.findElement(By.id("form-gen-submit")).click()
    // 17 | click | css=.-row .form-check:nth-child(1) > .form-check-label | 
    await driver.findElement(By.css(".-row .form-check:nth-child(1) > .form-check-label")).click()
    // 18 | click | id=iop_bus265-fnf | 
    await driver.findElement(By.id("iop_bus265-fnf")).click()
    // 19 | click | css=.-row .form-check:nth-child(3) | 
    await driver.findElement(By.css(".-row .form-check:nth-child(3)")).click()
    // 20 | click | id=iop_bus265-f_equity | 
    await driver.findElement(By.id("iop_bus265-f_equity")).click()
    // 21 | click | id=iop_bus265-pri_equity | 
    await driver.findElement(By.id("iop_bus265-pri_equity")).click()
    // 22 | click | id=iop_bus262-fin | 
    await driver.findElement(By.id("iop_bus262-fin")).click()
    // 23 | click | name=expl[fin] | 
    await driver.findElement(By.name("expl[fin]")).click()
    // 24 | type | name=expl[fin] | Random financial Source
    await driver.findElement(By.name("expl[fin]")).sendKeys("Random financial Source")
    // 25 | click | id=iop_bus262-nat | 
    await driver.findElement(By.id("iop_bus262-nat")).click()
    // 26 | click | name=expl[nat] | 
    await driver.findElement(By.name("expl[nat]")).click()
    // 27 | type | name=expl[nat] | Random Access to Natural sources
    await driver.findElement(By.name("expl[nat]")).sendKeys("Random Access to Natural sources")
    // 28 | click | id=iop_bus262-own | 
    await driver.findElement(By.id("iop_bus262-own")).click()
    // 29 | click | name=expl[own] | 
    await driver.findElement(By.name("expl[own]")).click()
    // 30 | type | name=expl[own] | Ownership
    await driver.findElement(By.name("expl[own]")).sendKeys("Ownership")
    // 31 | click | id=iop_bus263 | 
    await driver.findElement(By.id("iop_bus263")).click()
    // 32 | type | id=iop_bus263 | 86
    await driver.findElement(By.id("iop_bus263")).sendKeys("86")
    // 33 | click | id=iop_bus267 | 
    await driver.findElement(By.id("iop_bus267")).click()
    // 34 | type | id=iop_bus267 | 56.00
    await driver.findElement(By.id("iop_bus267")).sendKeys("56.00")
    // 35 | click | id=iop_bus268 | 
    await driver.findElement(By.id("iop_bus268")).click()
    // 36 | type | id=iop_bus268 | 89.00
    await driver.findElement(By.id("iop_bus268")).sendKeys("89.00")
    // 37 | click | id=iop_bus269 | 
    await driver.findElement(By.id("iop_bus269")).click()
    // 38 | type | id=iop_bus269 | 36.00
    await driver.findElement(By.id("iop_bus269")).sendKeys("36.00")
    // 39 | click | id=iop_bus270 | 
    await driver.findElement(By.id("iop_bus270")).click()
    // 40 | type | id=iop_bus270 | 14.00
    await driver.findElement(By.id("iop_bus270")).sendKeys("14.00")
    // 41 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 42 | click | id=iop_bus901 | 
    await driver.findElement(By.id("iop_bus901")).click()
    // 43 | type | id=iop_bus901 | Untitled Project for 2020
    await driver.findElement(By.id("iop_bus901")).sendKeys("Untitled Project for 2020")
    // 44 | click | id=iop_bus902 | 
    await driver.findElement(By.id("iop_bus902")).click()
    // 45 | click | id=iop_bus903 | 
    await driver.findElement(By.id("iop_bus903")).click()
    // 46 | type | id=iop_bus903 | Random Project Status
    await driver.findElement(By.id("iop_bus903")).sendKeys("Random Project Status")
    // 47 | type | id=iop_bus902 | Randome Project DEscription
    await driver.findElement(By.id("iop_bus902")).sendKeys("Randome Project DEscription")
    // 48 | click | id=iop_bus905 | 
    await driver.findElement(By.id("iop_bus905")).click()
    // 49 | type | id=iop_bus905 | 122457888
    await driver.findElement(By.id("iop_bus905")).sendKeys("122457888")
    // 50 | mouseOver | css=.select2-chosen | 
    {
      const element = await driver.findElement(By.css(".select2-chosen"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 51 | mouseOut | css=.select2-chosen | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 52 | click | css=body | 
    await driver.findElement(By.css("body")).click()
    // 53 | mouseDown | id=select2-drop-mask | 
    {
      const element = await driver.findElement(By.id("select2-drop-mask"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 54 | mouseUp | css=.select2-chosen | 
    {
      const element = await driver.findElement(By.css(".select2-chosen"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 55 | click | css=body | 
    await driver.findElement(By.css("body")).click()
    // 56 | click | css=.mb-2 > label | 
    await driver.findElement(By.css(".mb-2 > label")).click()
    // 57 | click | css=.iop_bus907-row .form-check:nth-child(1) > .form-check-label | 
    await driver.findElement(By.css(".iop_bus907-row .form-check:nth-child(1) > .form-check-label")).click()
    // 58 | click | css=.iop_bus907-row .form-check:nth-child(4) > .form-check-label | 
    await driver.findElement(By.css(".iop_bus907-row .form-check:nth-child(4) > .form-check-label")).click()
    // 59 | click | css=.iop_bus907-row > .controls | 
    await driver.findElement(By.css(".iop_bus907-row > .controls")).click()
    // 60 | click | css=.iop_bus907-row .form-check:nth-child(7) > .form-check-label | 
    await driver.findElement(By.css(".iop_bus907-row .form-check:nth-child(7) > .form-check-label")).click()
    // 61 | click | css=.form-check:nth-child(9) > .form-check-label | 
    await driver.findElement(By.css(".form-check:nth-child(9) > .form-check-label")).click()
    // 62 | click | css=.iop_bus906-row .form-check:nth-child(2) > .form-check-label | 
    await driver.findElement(By.css(".iop_bus906-row .form-check:nth-child(2) > .form-check-label")).click()
    // 63 | click | css=.iop_bus906-row .form-check:nth-child(4) > .form-check-label | 
    await driver.findElement(By.css(".iop_bus906-row .form-check:nth-child(4) > .form-check-label")).click()
    // 64 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 65 | mouseOver | css=.btn | 
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 66 | mouseOut | css=.btn | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 67 | click | css=.iop_bus272-row .form-check:nth-child(2) > .form-check-label | 
    await driver.findElement(By.css(".iop_bus272-row .form-check:nth-child(2) > .form-check-label")).click()
    // 68 | click | id=iop_bus272-debt | 
    await driver.findElement(By.id("iop_bus272-debt")).click()
    // 69 | click | css=.iop_bus274-row .form-check:nth-child(4) > .form-check-label | 
    await driver.findElement(By.css(".iop_bus274-row .form-check:nth-child(4) > .form-check-label")).click()
    // 70 | click | css=.iop_bus274-row .form-check:nth-child(3) > .form-check-label | 
    await driver.findElement(By.css(".iop_bus274-row .form-check:nth-child(3) > .form-check-label")).click()
    // 71 | click | css=.iop_bus274-row .form-check:nth-child(2) > .form-check-label | 
    await driver.findElement(By.css(".iop_bus274-row .form-check:nth-child(2) > .form-check-label")).click()
    // 72 | click | id=iop_bus280-b_int | 
    await driver.findElement(By.id("iop_bus280-b_int")).click()
    // 73 | click | id=iop_bus280-exp_mrt | 
    await driver.findElement(By.id("iop_bus280-exp_mrt")).click()
    // 74 | click | id=iop_bus280-nw_prod | 
    await driver.findElement(By.id("iop_bus280-nw_prod")).click()
    // 75 | click | id=iop_bus280-ex_dom | 
    await driver.findElement(By.id("iop_bus280-ex_dom")).click()
    // 76 | click | id=iop_bus757 | 
    await driver.findElement(By.id("iop_bus757")).click()
    // 77 | type | id=iop_bus757 | Every other investment
    await driver.findElement(By.id("iop_bus757")).sendKeys("Every other investment")
    // 78 | click | id=iop_bus278 | 
    await driver.findElement(By.id("iop_bus278")).click()
    // 79 | type | id=iop_bus278 | 67898
    await driver.findElement(By.id("iop_bus278")).sendKeys("67898")
    // 80 | click | css=.col-md-6:nth-child(1) > .row:nth-child(4) > .col-md-12 | 
    await driver.findElement(By.css(".col-md-6:nth-child(1) > .row:nth-child(4) > .col-md-12")).click()
    // 81 | click | id=iop_bus279 | 
    await driver.findElement(By.id("iop_bus279")).click()
    // 82 | type | id=iop_bus279 | Random Investment Purposes
    await driver.findElement(By.id("iop_bus279")).sendKeys("Random Investment Purposes")
    // 83 | click | id=iop_bus287 | 
    await driver.findElement(By.id("iop_bus287")).click()
    // 84 | type | id=iop_bus287 | 889
    await driver.findElement(By.id("iop_bus287")).sendKeys("889")
    // 85 | click | id=iop_bus288 | 
    await driver.findElement(By.id("iop_bus288")).click()
    // 86 | type | id=iop_bus288 | 754
    await driver.findElement(By.id("iop_bus288")).sendKeys("754")
    // 87 | click | id=iop_bus297 | 
    await driver.findElement(By.id("iop_bus297")).click()
    // 88 | type | id=iop_bus297 | 1345
    await driver.findElement(By.id("iop_bus297")).sendKeys("1345")
    // 89 | click | id=iop_bus289 | 
    await driver.findElement(By.id("iop_bus289")).click()
    // 90 | type | id=iop_bus289 | 2522
    await driver.findElement(By.id("iop_bus289")).sendKeys("2522")
    // 91 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 92 | mouseOver | css=.btn | 
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 93 | mouseOut | css=.btn | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 94 | click | name=date_prev | 
    await driver.findElement(By.name("date_prev")).click()
    // 95 | click | id=iop_bus290 | 
    await driver.findElement(By.id("iop_bus290")).click()
    // 96 | select | id=iop_bus290 | label=No
    {
      const dropdown = await driver.findElement(By.id("iop_bus290"))
      await dropdown.findElement(By.xpath("//option[. = 'No']")).click()
    }
    // 97 | click | name=submit | 
    await driver.findElement(By.name("submit")).click()
    // 98 | mouseOver | name=submit | 
    {
      const element = await driver.findElement(By.name("submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 99 | mouseOut | name=submit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 100 | click | id=iop_bus247 | 
    await driver.findElement(By.id("iop_bus247")).click()
    // 101 | type | id=iop_bus247 | Random selenium details
    await driver.findElement(By.id("iop_bus247")).sendKeys("Random selenium details")
    // 102 | click | css=.form-check:nth-child(1) > .form-check-label | 
    await driver.findElement(By.css(".form-check:nth-child(1) > .form-check-label")).click()
    // 103 | click | css=.form-check:nth-child(2) > .form-check-label | 
    await driver.findElement(By.css(".form-check:nth-child(2) > .form-check-label")).click()
    // 104 | click | css=.form-check:nth-child(3) > .form-check-label | 
    await driver.findElement(By.css(".form-check:nth-child(3) > .form-check-label")).click()
    // 105 | click | id=iop_bus250 | 
    await driver.findElement(By.id("iop_bus250")).click()
    // 106 | type | id=iop_bus250 | Other Randome Information
    await driver.findElement(By.id("iop_bus250")).sendKeys("Other Randome Information")
    // 107 | click | id=form-gen-submit | 
    await driver.findElement(By.id("form-gen-submit")).click()
    // 108 | mouseOver | id=form-gen-submit | 
    {
      const element = await driver.findElement(By.id("form-gen-submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 109 | mouseOut | id=form-gen-submit | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 110 | click | name=owners[name][] | 
    await driver.findElement(By.name("owners[name][]")).click()
    // 111 | click | name=owners[name][] | 
    await driver.findElement(By.name("owners[name][]")).click()
    // 112 | type | name=owners[name][] | Joseph Marcus
    await driver.findElement(By.name("owners[name][]")).sendKeys("Joseph Marcus")
    // 113 | click | name=owners[position][] | 
    await driver.findElement(By.name("owners[position][]")).click()
    // 114 | type | name=owners[position][] | CEO
    await driver.findElement(By.name("owners[position][]")).sendKeys("CEO")
    // 115 | click | name=owners[telephone][] | 
    await driver.findElement(By.name("owners[telephone][]")).click()
    // 116 | type | name=owners[telephone][] | +9876543456789
    await driver.findElement(By.name("owners[telephone][]")).sendKeys("+9876543456789")
    // 117 | click | css=.owner-row > .col-md-3:nth-child(4) | 
    await driver.findElement(By.css(".owner-row > .col-md-3:nth-child(4)")).click()
    // 118 | click | name=owners[email][] | 
    await driver.findElement(By.name("owners[email][]")).click()
    // 119 | type | name=owners[email][] | andrea.johnson@hotmail.com
    await driver.findElement(By.name("owners[email][]")).sendKeys("andrea.johnson@hotmail.com")
    // 120 | click | name=submit | 
    await driver.findElement(By.name("submit")).click()
    // 121 | mouseOver | name=submit | 
    {
      const element = await driver.findElement(By.name("submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 122 | click | name=file | 
    await driver.findElement(By.name("file")).click()
  })
})
