// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('IOP Login and Start Registration', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('IOP Login and Start Registration', async function() {
    // Test name: IOP Login and Start Registration
    // Step # | name | target | value
    // 1 | open | /solutions/nipc/ | 
    await driver.get("http://localhost:819/solutions/nipc/solutions/nipc/")
    // 2 | setWindowSize | 1237x864 | 
    await driver.manage().window().setRect({ width: 1237, height: 864 })
    // 3 | click | linkText=Sign In | 
    await driver.findElement(By.linkText("Sign In")).click()
    // 4 | runScript | window.scrollTo(0,488) | 
    await driver.executeScript("window.scrollTo(0,488)")
    // 5 | click | css=.submit-border > input | 
    await driver.findElement(By.css(".submit-border > input")).click()
    // 6 | click | css=.list-group-item-action:nth-child(3) | 
    await driver.findElement(By.css(".list-group-item-action:nth-child(3)")).click()
    // 7 | click | id=sub-menu-b_biz | 
    await driver.findElement(By.id("sub-menu-b_biz")).click()
    // 8 | click | linkText=link | 
    await driver.findElement(By.linkText("link")).click()
    // 9 | click | id=eosic_company8 | 
    await driver.findElement(By.id("eosic_company8")).click()
    // 10 | type | id=eosic_company8 | 3336584
    await driver.findElement(By.id("eosic_company8")).sendKeys("3336584")
    // 11 | click | id=eosic_company9 | 
    await driver.findElement(By.id("eosic_company9")).click()
    // 12 | type | id=eosic_company9 | hdjhdlnjhho
    await driver.findElement(By.id("eosic_company9")).sendKeys("hdjhdlnjhho")
    // 13 | click | id=eosic_company7 | 
    await driver.findElement(By.id("eosic_company7")).click()
    // 14 | type | id=eosic_company7 | 2021-11-16
    await driver.findElement(By.id("eosic_company7")).sendKeys("2021-11-16")
    // 15 | click | id=eosic_company748 | 
    await driver.findElement(By.id("eosic_company748")).click()
    // 16 | type | id=eosic_company748 | 2021-11-16
    await driver.findElement(By.id("eosic_company748")).sendKeys("2021-11-16")
    // 17 | click | id=eosic_company10 | 
    await driver.findElement(By.id("eosic_company10")).click()
    // 18 | type | id=eosic_company10 | 5B Bello Street, Chenchenia, Kaduna Road
    await driver.findElement(By.id("eosic_company10")).sendKeys("5B Bello Street, Chenchenia, Kaduna Road")
    // 19 | mouseOver | css=.select2-chosen | 
    {
      const element = await driver.findElement(By.css(".select2-chosen"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 20 | mouseOut | css=.select2-chosen | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 21 | mouseDown | css=.select2-chosen | 
    {
      const element = await driver.findElement(By.css(".select2-chosen"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 22 | mouseUp | id=select2-drop-mask | 
    {
      const element = await driver.findElement(By.id("select2-drop-mask"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 23 | click | css=body | 
    await driver.findElement(By.css("body")).click()
    // 24 | click | id=eosic_company11 | 
    await driver.findElement(By.id("eosic_company11")).click()
    // 25 | type | id=eosic_company11 | +256101101010
    await driver.findElement(By.id("eosic_company11")).sendKeys("+256101101010")
    // 26 | click | id=bottom-row-container | 
    await driver.findElement(By.id("bottom-row-container")).click()
    // 27 | click | id=eosic_company285 | 
    await driver.findElement(By.id("eosic_company285")).click()
    // 28 | type | id=eosic_company285 | random34@mail.com
    await driver.findElement(By.id("eosic_company285")).sendKeys("random34@mail.com")
    // 29 | click | css=.select2-choices | 
    await driver.findElement(By.css(".select2-choices")).click()
    // 30 | click | id=eosic_company12 | 
    await driver.findElement(By.id("eosic_company12")).click()
    // 31 | type | id=eosic_company12 | random words selenium test
    await driver.findElement(By.id("eosic_company12")).sendKeys("random words selenium test")
    // 32 | click | id=form-gen-submit | 
    await driver.findElement(By.id("form-gen-submit")).click()
    // 33 | mouseOver | id=form-gen-submit | 
    {
      const element = await driver.findElement(By.id("form-gen-submit"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 34 | click | id=sub-menu-b_finish | 
    await driver.findElement(By.id("sub-menu-b_finish")).click()
    // 35 | close |  | 
    await driver.close()
  })
})
