// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PSI Login and Start Registration', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PSI Login and Start Registration', async function() {
    await driver.get("http://localhost:819/solutions/nipc/")
    await driver.manage().window().setRect({ width: 1552, height: 880 })
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.switchTo().frame(0)
    await driver.findElement(By.css(".recaptcha-checkbox-border")).click()
    await driver.switchTo().defaultContent()
    await driver.findElement(By.css(".submit-border > input")).click()
    await driver.findElement(By.css(".list-group-item-action:nth-child(4)")).click()
    await driver.findElement(By.id("sub-menu-b_biz")).click()
    {
      const element = await driver.findElement(By.id("sub-menu-b_biz"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("link")).click()
    await driver.findElement(By.id("eosic_company749")).click()
    await driver.findElement(By.id("eosic_company749")).sendKeys("09876543")
    await driver.findElement(By.id("eosic_company9")).sendKeys("New Random PSI Company")
    await driver.findElement(By.id("eosic_company10")).click()
    await driver.findElement(By.id("eosic_company10")).sendKeys("5B Bello Street, Chenchenia, Kaduna Road")
    await driver.findElement(By.id("eosic_company11")).click()
    await driver.findElement(By.id("eosic_company11")).sendKeys("+256101101010")
    await driver.findElement(By.id("eosic_company285")).click()
    await driver.findElement(By.id("eosic_company285")).sendKeys("random34@mail.com")
    await driver.findElement(By.css(".select2-choices")).click()
    await driver.findElement(By.id("eosic_company756")).click()
    await driver.findElement(By.id("eosic_company756")).sendKeys("https://www.dangerouscorp.com")
    await driver.findElement(By.id("eosic_company756")).click()
    await driver.findElement(By.id("eosic_company756")).click()
    {
      const element = await driver.findElement(By.id("eosic_company756"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("eosic_company756")).sendKeys("https://www.newrandom.com")
    await driver.findElement(By.id("contact")).click()
    await driver.findElement(By.id("contact")).sendKeys("Ayalash Joseph")
    await driver.findElement(By.id("dsgn")).click()
    await driver.findElement(By.id("dsgn")).sendKeys("Mr")
    await driver.findElement(By.id("c_phone")).click()
    await driver.findElement(By.id("c_phone")).sendKeys("+55665552284")
    await driver.findElement(By.id("c_email")).click()
    await driver.findElement(By.id("c_email")).sendKeys("mail@randomcomp.hotmail")
    await driver.findElement(By.name("file")).click()
    await driver.findElement(By.css(".qq-upload-button-hover > .form-control")).click()
    await driver.findElement(By.id("form-gen-submit")).click()
  })
})
