// Generated by Selenium IDE
const { Builder, By } = require('selenium-webdriver')
const assert = require('assert')
const config = require('./config');

describe('Login and Start Application', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login and Start Application', async function() {
    // await driver.get("http://localhost:819/solutions/nipc/")
    await driver.get(config[ config.env ].url);
    await driver.manage().window().setRect({ width: 1200, height: 960 })
    await driver.findElement(By.linkText("Sign In")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("john.doe@hotmail.com")
    await driver.findElement(By.name("password")).sendKeys("johndoejohn")
    await driver.findElement(By.css(".submit-border > input")).click()
    await driver.findElement(By.css(".list-group-item-action:nth-child(4)")).click()
    await driver.findElement(By.id("sub-menu-b_qcri")).click()
    {
      const element = await driver.findElement(By.css(".select2-chosen"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.id("psi_criteria323")).click()
    await driver.findElement(By.id("psi_criteria323")).sendKeys("Pioneer Product")
    await driver.findElement(By.id("form-gen-submit")).click()
    await driver.findElement(By.linkText("link")).click()
    assert(await driver.switchTo().alert().getText() == "Open File Directory")
    await driver.switchTo().alert().dismiss()
    await driver.findElement(By.id("eosic_company8")).sendKeys("Hagenes, Lesch and Franecki")
    await driver.findElement(By.id("eosic_company749")).sendKeys("Veum Group")
    await driver.findElement(By.id("eosic_company9")).sendKeys("Corkery, Hintz and Kreiger")
    await driver.findElement(By.id("eosic_company10")).sendKeys("92 Johns Expressway")
    await driver.findElement(By.id("s2id_autogen2")).sendKeys("mali")
    await driver.findElement(By.id("eosic_company371")).sendKeys("Collier, Carter and Kunze")
    await driver.findElement(By.id("eosic_company11")).sendKeys("861-214-6200")
    await driver.findElement(By.id("eosic_company285")).sendKeys("your.email+fakedata77977@gmail.com")
    await driver.findElement(By.id("eosic_company370")).sendKeys("Wehner, Murray and Feil")
    await driver.findElement(By.id("contact")).sendKeys("Mauritania")
    await driver.findElement(By.id("dsgn")).sendKeys("Ea voluptatem quis deserunt totam.")
    await driver.findElement(By.id("c_phone")).sendKeys("173-840-5447")
    await driver.findElement(By.id("c_email")).sendKeys("your.email+fakedata44205@gmail.com")
    await driver.findElement(By.id("eosic_company750")).sendKeys("Breitenberg, Steuber and Ullrich")
    await driver.findElement(By.id("eosic_company751")).sendKeys("464-698-4861")
    await driver.findElement(By.id("eosic_company11")).click()
    await driver.findElement(By.id("eosic_company11")).sendKeys("+8612146200")
    await driver.findElement(By.id("phone-address-toggle")).click()
    await driver.findElement(By.id("eosic_company285")).click()
    await driver.findElement(By.id("eosic_company285")).sendKeys("fakedata77977@gmail.com")
    await driver.findElement(By.id("s2id_autogen3")).click()
    await driver.findElement(By.id("eosic_company756")).click()
    await driver.findElement(By.id("eosic_company756")).click()
    await driver.findElement(By.id("eosic_company756")).sendKeys("https://www.website.com")
    await driver.findElement(By.id("c_email")).click()
    await driver.findElement(By.id("c_email")).click()
    {
      const element = await driver.findElement(By.id("c_email"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("c_email")).sendKeys("fakedata44205@gmail.com")
    await driver.findElement(By.id("form-gen-submit")).click()
    await driver.findElement(By.id("c_phone")).click()
    await driver.findElement(By.id("c_phone")).sendKeys("+1738405447")
    await driver.findElement(By.id("form-gen-submit")).click()
    assert(await driver.switchTo().alert().getText() == "Open File Directory")
    await driver.switchTo().alert().dismiss()
    {
      const dropdown = await driver.findElement(By.id("psi_criteria770"))
      await dropdown.findElement(By.xpath("//option[. = 'No']")).click()
    }
    await driver.findElement(By.id("psi_criteria843")).sendKeys("Tenetur veritatis sed ullam enim porro rerum occaecati sunt.")
    await driver.findElement(By.id("psi_criteria324")).sendKeys("Molestiae quaerat ad illum dolor dolorem.")
    await driver.findElement(By.id("s2id_autogen4")).sendKeys("New")
    await driver.findElement(By.id("psi_criteria325")).sendKeys("Pariatur suscipit nostrum eum dignissimos quae in quisquam fugiat eum.")
    await driver.findElement(By.id("psi_criteria330")).sendKeys("Consectetur sed dicta impedit voluptatem facilis.")
    await driver.findElement(By.id("psi_criteria343")).sendKeys("Quia quis non facilis vel quia.")
    await driver.findElement(By.id("psi_criteria344")).sendKeys("483-243-6702")
    await driver.findElement(By.id("psi_criteria345")).sendKeys("Illum dolores ipsam laudantium doloremque.")
    await driver.findElement(By.id("psi_criteria346")).sendKeys("Modi facilis atque vel voluptates.")
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.id("psi_criteria770")).click()
    {
      const dropdown = await driver.findElement(By.id("psi_criteria770"))
      await dropdown.findElement(By.xpath("//option[. = 'Yes']")).click()
    }
    {
      const element = await driver.findElement(By.css(".select2-chosen"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.id("psi_criteria843")).click()
    assert(await driver.switchTo().alert().getText() == "Open File Directory")
    await driver.switchTo().alert().dismiss()
    await driver.findElement(By.id("psi_criteria843")).sendKeys("Watsica, Weissnat and Olson")
    await driver.findElement(By.id("psi_criteria843")).sendKeys("Watsica, Weissnat and Olson")
    await driver.findElement(By.id("form-gen-submit")).click()
    await driver.findElement(By.id("psi_criteria344")).sendKeys("+4832436702")
    await driver.findElement(By.id("form-gen-submit")).click()
    await driver.findElement(By.name("submit")).click()
    await driver.findElement(By.css(".finish-btn")).click()
    await driver.findElement(By.id("sub-menu-b_biz")).click()
    await driver.findElement(By.id("eosic_company8")).click()
    await driver.findElement(By.id("eosic_company8")).sendKeys("78999955")
    await driver.findElement(By.id("eosic_company749")).sendKeys("1234569")
    await driver.findElement(By.id("form-gen-submit")).click()
    await driver.findElement(By.id("sub-menu-b_finish")).click()
    {
      const element = await driver.findElement(By.id("sub-menu-b_finish"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".text-centerX > label")).click()
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.switchTo().alert().getText() == "Are you sure you want to submit this form?")
    await driver.switchTo().alert().accept()
    await driver.findElement(By.css(".sidebar")).click()
    await driver.findElement(By.css(".sidebar-menu")).click()
    await driver.findElement(By.css("li:nth-child(9) span")).click()
    await driver.close()
  })
})
